### ISSUE TITLE
Unable to get complex data structure as input in custom component

### ISSUE THREAD

**Issue by AliKhalili** [prismatic-io/examples#33]
I publish `data-example` component and use that in a flow but it seems it does not work as we expected:
![image](https://user-images.githubusercontent.com/524539/166926938-4253f326-a097-4198-82e2-6d60e4a03c79.png)

and the output result is:
![image](https://user-images.githubusercontent.com/524539/166927006-073b62ea-1866-4b51-8054-03a1724a6337.png)
could please check what's wrong with that?

**Comment by taylorreece** [comment]
Hi @AliKhalili - great question and observation! The problem you're seeing boils down to what inputs looks like when they reach an action's `perform` function.

By default an input field is a simple string. That string could contain anything - JSON, XML, CSV, etc. We don't make assumption about what data you're going to pass in.

What's going on in your screenshot is that you're providing a JSON-like string as input, but the action's perform function doesn't know how to handle JSON strings. The first `const { productName, quantity, price } = params.pointOfSale;` line in the perform function winds up setting all of those variables to `undefined` because it's trying to destructure a string. It's effectively doing this:

```
> const { foo, bar } = "Some String"
undefined
> foo
undefined
> bar
undefined
```

So... there's a couple of things you can do here:

## Reference a JavaScript Object Instead

The goal of this sample component is to show off passing a JavaScript object from one step to another.
Add a [code step](https://prismatic.io/docs/components/code/) to your integration, and have it read something like this:

```javascript
module.exports = async (context, stepResults) => {
  return {
    data: {
      productName: "Widget",
      price: 1.25,
      quantity: 75,
    },
  };
};
```

Then, you can reference that step's results as your action's input. That way, your action will get a JavaScript object instead of a JSON-like string:

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/3622586/166986490-e5580139-447c-425d-a29d-70606e640dd7.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/3622586/166986620-81e5d566-8c5e-40e7-b7b5-187e4fdb4500.png">

## Support JSON Strings

But what if we wanted to support JSON strings? You could modify the `perform` function to check if the input is a JSON string, and if so, do a `JSON.parse()` on that string. If you did that, then you could pass in valid JSON (with double-quotes around keys and values like `{"productName":"Widget","price":1.25,"quantity":75}` as an input, that the action would still accept it:

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/3622586/166986932-9e1c430e-b865-4205-ba0a-2603a9f274cc.png">

I thought that'd be a good thing to show off, so I went ahead and added JSON parsing with this commit: https://github.com/prismatic-io/examples/commit/3b3c423344c921147553db9c61db186edff0be40

Note that I bumped @prismatic-io/spectral to the latest version, and took advantage of the new "clean" function that we just released, whose job it is to clean up input and ensure it's in a proper format.

---

Does that make sense? Please give me a shout if you'd like to chat more, or have any other questions!

**Comment by AliKhalili** [comment]
Thank you so much for your great explanation. That worked for me very well. I didn't know about the clean function.
